/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
public class CarbonFootprint extends javax.swing.JFrame {
    private UserDAO userDAO; 
    private int userId;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CarbonFootprint.class.getName());
    // 🌟 Variable tracking token for the active logged-in user session profile
    private int currentSessionUserId;
    /**
     * Creates new form CarbonFootprint
     */
    /**
    * Creates new form CarbonFootprint with dynamic session tracking parameters.
    */
    public CarbonFootprint(int userId) {
        // 2. Assigns the login token to the class variable
        this.currentSessionUserId = userId; 
    
        initComponents();
        this.setLocationRelativeTo(null);
    
        // Pre-populate table at window startup
        populateHistoryLogTable(this.currentSessionUserId > 0 ? this.currentSessionUserId : 1);
    }

    // Default fallback constructor so you can test via Shift+F6 directly
    public CarbonFootprint() {
        this(1); 
    }
    
    public void populateHistoryLogTable(int userId) {
        // 1. Set up headers matching your interface layout
        java.util.Vector<String> columns = new java.util.Vector<>(java.util.Arrays.asList(
            "Activity Type", "Details / Vehicle", "Usage Value", "Carbon Footprint (kg CO2e)", "Log Date"
        ));
        java.util.Vector<java.util.Vector<Object>> data = new java.util.Vector<>();

        // 2. Query filtered by the logged-in user's ID to keep entries isolated per user account
        String sql = "SELECT category, details, activity_usage, calculated_co2e, log_date FROM emission_logs " +
                 "WHERE user_id = ? ORDER BY log_date DESC";

        try (Connection conn = DBConnection.getConnection();
            PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
            pstmt.setInt(1, userId);
        
            try (ResultSet rs = pstmt.executeQuery()) {
                while (rs.next()) {
                    java.util.Vector<Object> row = new java.util.Vector<>();
                    row.add(rs.getString("category"));          // 'Transport' or 'Utilities'
                    row.add(rs.getString("details"));           // e.g., 'Car (Petrol)' or 'Electricity'
                    row.add(rs.getDouble("activity_usage"));     // Distance value or kWh value
                    row.add(rs.getBigDecimal("calculated_co2e"));// Footprint mass matching database float
                    row.add(rs.getTimestamp("log_date"));        // Record creation date timestamp
                    data.add(row);
                }
            }
        
            // 3. Directly update your shared variable table model view
            tblHistoryLog.setModel(new javax.swing.table.DefaultTableModel(data, columns));
        
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbVehicleType = new javax.swing.JComboBox<>();
        fuelTypeCombo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        distanceSpinner = new javax.swing.JSpinner();
        logTransportBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        electricitySpinner = new javax.swing.JSpinner();
        btnLogElectricity = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistoryLog = new javax.swing.JTable();
        dashboardBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CARBON FOOTPRINT TRACKER");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Vehicle Type   :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Fuel Type        :");

        cmbVehicleType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbVehicleType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Bus", "Bike", "Cycle", "Walk" }));
        cmbVehicleType.addActionListener(this::cmbVehicleTypeActionPerformed);

        fuelTypeCombo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fuelTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Petrol / CNG", "Diesel", "Electric", "None" }));
        fuelTypeCombo.addActionListener(this::fuelTypeComboActionPerformed);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Distance (km) :");

        distanceSpinner.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        logTransportBtn.setBackground(new java.awt.Color(51, 102, 0));
        logTransportBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logTransportBtn.setForeground(new java.awt.Color(204, 255, 204));
        logTransportBtn.setText("Log Transport");
        logTransportBtn.addActionListener(this::logTransportBtnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fuelTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbVehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distanceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(logTransportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbVehicleType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fuelTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(distanceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(logTransportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transport Log", jPanel1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Electricity Used Today (kWh) :");

        electricitySpinner.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnLogElectricity.setBackground(new java.awt.Color(51, 102, 0));
        btnLogElectricity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogElectricity.setForeground(new java.awt.Color(204, 255, 204));
        btnLogElectricity.setText("Log Electricity");
        btnLogElectricity.addActionListener(this::btnLogElectricityActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(electricitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnLogElectricity, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(electricitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(btnLogElectricity, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Utilities Log", jPanel2);

        tblHistoryLog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblHistoryLog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHistoryLog);

        dashboardBtn1.setBackground(new java.awt.Color(51, 102, 0));
        dashboardBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dashboardBtn1.setForeground(new java.awt.Color(204, 255, 204));
        dashboardBtn1.setText("Dashboard");
        dashboardBtn1.addActionListener(this::dashboardBtn1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dashboardBtn1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboardBtn1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbVehicleTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVehicleTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVehicleTypeActionPerformed

    private void fuelTypeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelTypeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelTypeComboActionPerformed

    private void logTransportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logTransportBtnActionPerformed
        Object spinnerValue = distanceSpinner.getValue();
    
        if (spinnerValue == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a valid distance!", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
    
        try {
            double distance = ((Number) spinnerValue).doubleValue(); 
            if (distance <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Distance must be greater than zero!", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            String vehicleType = cmbVehicleType.getSelectedItem().toString();
            // Calculation matching image_4.png baseline specs (e.g., Petrol Car = 0.170)
            double carbonEmitted = distance * 0.170; 

            // Match columns seen in image_5.png: user_id, category, details, activity_usage, calculated_co2e, log_date
            String sql = "INSERT INTO emission_logs (user_id, category, details, activity_usage, calculated_co2e, log_date) VALUES (?, 'Transport', ?, ?, ?, NOW())";
        
            try (Connection conn = DBConnection.getConnection();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
                int activeUser = (this.currentSessionUserId > 0) ? this.currentSessionUserId : 1; 
            
                pstmt.setInt(1, activeUser);
                pstmt.setString(2, vehicleType);
                pstmt.setDouble(3, distance);
                pstmt.setDouble(4, carbonEmitted);
            
                int rowsInserted = pstmt.executeUpdate();
                if (rowsInserted > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Transport activity logged successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    distanceSpinner.setValue(0); // Clear spinner entry
    
                    // REFRESH TABLE: Forces table to pull the current user's updated database data rows
                    populateHistoryLogTable(activeUser); // Refresh history
                }
            }
            } catch (SQLException e) {
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Database Write Error: " + e.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_logTransportBtnActionPerformed

    private void btnLogElectricityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogElectricityActionPerformed
        Object spinnerValue = electricitySpinner.getValue();
    
        if (spinnerValue == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please select a valid consumption value!", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
    
        try {
            double kwh = ((Number) spinnerValue).doubleValue(); 
            if (kwh <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Electricity consumption must be greater than zero!", "Input Error", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
        
            // Calculation factor: approx 0.45 kg CO2e per kWh
            double carbonEmitted = kwh * 0.45; 
        
            // Match columns seen in image_5.png: user_id, category, details, activity_usage, calculated_co2e, log_date
            String sql = "INSERT INTO emission_logs (user_id, category, details, activity_usage, calculated_co2e, log_date) VALUES (?, 'Utilities', 'Electricity', ?, ?, NOW())";
        
            try (Connection conn = DBConnection.getConnection();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {
            
                int activeUser = (this.currentSessionUserId > 0) ? this.currentSessionUserId : 1;
            
                pstmt.setInt(1, activeUser);
                pstmt.setDouble(2, kwh);
                pstmt.setDouble(3, carbonEmitted);
            
                int rowsInserted = pstmt.executeUpdate();
                if (rowsInserted > 0) {
                    javax.swing.JOptionPane.showMessageDialog(this, "Electricity log saved successfully!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                    electricitySpinner.setValue(0); // Clear spinner entry
    
                    // REFRESH TABLE: Synchronizes the shared history view table with new entries
                    populateHistoryLogTable(activeUser); // Refresh history
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "SQL Write Error: " + e.getMessage(), "Database Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnLogElectricityActionPerformed

    private void dashboardBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtn1ActionPerformed
        // TODO add your handling code here:
        Dashboard dash = new Dashboard();
        dash.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CarbonFootprint().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogElectricity;
    private javax.swing.JComboBox<String> cmbVehicleType;
    private javax.swing.JButton dashboardBtn1;
    private javax.swing.JSpinner distanceSpinner;
    private javax.swing.JSpinner electricitySpinner;
    private javax.swing.JComboBox<String> fuelTypeCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logTransportBtn;
    private javax.swing.JTable tblHistoryLog;
    // End of variables declaration//GEN-END:variables
}
