/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */

public class Challenges extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Challenges.class.getName());
    private int userId;
    /**
     * Creates new form Challanges
     */
     public Challenges(int sessionUserId) {
        this.userId = sessionUserId; // Save the passed user token globally
        initComponents();
        this.setLocationRelativeTo(null); // Center frame window screen
    }
    public Challenges() {
        this(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        chkMonthly1 = new javax.swing.JCheckBox();
        chkWeekly3 = new javax.swing.JCheckBox();
        chkWeekly2 = new javax.swing.JCheckBox();
        chkMonthly2 = new javax.swing.JCheckBox();
        chkDaily2 = new javax.swing.JCheckBox();
        chkMonthly3 = new javax.swing.JCheckBox();
        chkDaily3 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        chkWeekly1 = new javax.swing.JCheckBox();
        chkDaily1 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 102, 0));
        jLabel13.setText("Green Challenges");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("2.Carry a reusable water bottle");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Monthly Challenges");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Daily Challenges");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("1.Use public transport for an entire month");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("3.Avoid single-use plastic");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("2.Complete 20 daily challenges in a month");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Weekly Challenges");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("3.Collect and recycle e-waste");

        chkMonthly1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkMonthly1.setText("Completed");
        chkMonthly1.addActionListener(this::chkMonthly1ActionPerformed);

        chkWeekly3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkWeekly3.setText("Completed");
        chkWeekly3.addActionListener(this::chkWeekly3ActionPerformed);

        chkWeekly2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkWeekly2.setText("Completed");
        chkWeekly2.addActionListener(this::chkWeekly2ActionPerformed);

        chkMonthly2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkMonthly2.setText("Completed");
        chkMonthly2.addActionListener(this::chkMonthly2ActionPerformed);

        chkDaily2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkDaily2.setText("Completed");
        chkDaily2.addActionListener(this::chkDaily2ActionPerformed);

        chkMonthly3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkMonthly3.setText("Completed");
        chkMonthly3.addActionListener(this::chkMonthly3ActionPerformed);

        chkDaily3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkDaily3.setText("Completed");
        chkDaily3.addActionListener(this::chkDaily3ActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("1.Plant one tree");

        chkWeekly1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkWeekly1.setText("Completed");
        chkWeekly1.addActionListener(this::chkWeekly1ActionPerformed);

        chkDaily1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkDaily1.setText("Completed");
        chkDaily1.addActionListener(this::chkDaily1ActionPerformed);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("2.Save 20 liters of water");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("1.Walk or cycle for 2 km");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("3.Reduce electricity usage by 10%");

        btnSubmit.setBackground(new java.awt.Color(51, 102, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(204, 255, 204));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(this::btnSubmitActionPerformed);

        btnDashboard.setBackground(new java.awt.Color(51, 102, 0));
        btnDashboard.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDashboard.setForeground(new java.awt.Color(204, 255, 204));
        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(this::btnDashboardActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkDaily3)
                                    .addComponent(chkDaily1)
                                    .addComponent(chkDaily2)
                                    .addComponent(chkMonthly2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(chkWeekly3, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(chkWeekly2, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(chkWeekly1, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(chkMonthly1)
                                    .addComponent(chkMonthly3))))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102)
                        .addComponent(btnDashboard)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDashboard)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(chkWeekly1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(chkWeekly2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkWeekly3))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(chkMonthly1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(chkMonthly2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(chkMonthly3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkDaily1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(chkDaily2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkDaily3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkMonthly1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMonthly1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMonthly1ActionPerformed

    private void chkWeekly3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkWeekly3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkWeekly3ActionPerformed

    private void chkWeekly2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkWeekly2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkWeekly2ActionPerformed

    private void chkMonthly2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMonthly2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMonthly2ActionPerformed

    private void chkDaily2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDaily2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDaily2ActionPerformed

    private void chkMonthly3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMonthly3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMonthly3ActionPerformed

    private void chkDaily3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDaily3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDaily3ActionPerformed

    private void chkWeekly1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkWeekly1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkWeekly1ActionPerformed

    private void chkDaily1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDaily1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDaily1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        int accumulatedPoints = 0;

        //  FIX 1: Use the class variable 'this.userId' instead of hardcoding '1'
        int currentUserId = this.userId; 

        StringBuilder summaryMessage = new StringBuilder("Challenges Log Summary:\n");

        // 📅 Daily Tasks Section (Fixed Nested Logic Boundary)
        if (chkDaily1.isSelected()) { 
            accumulatedPoints += 15;
            summaryMessage.append("- Transit/Carpool Completed (+15 pts)\n");
        }
        if (chkDaily2.isSelected()) { 
            accumulatedPoints += 15;
            summaryMessage.append("- No Single-Use Plastic Completed (+15 pts)\n");
        }
        //  FIX 2: Extracted chkDaily3 out of chkDaily2 so it evaluates independently
        if (chkDaily3.isSelected()) { 
            accumulatedPoints += 15;
            summaryMessage.append("- Eco-Friendly Milestone Completed (+15 pts)\n");
        }

        // 🗓️ Weekly Tasks Section
        if (chkWeekly1.isSelected()) { 
            accumulatedPoints += 50;
            summaryMessage.append("- Planted Sapling Completed (+50 pts)\n");
        }
        if (chkWeekly2.isSelected()) { 
            accumulatedPoints += 50;
            summaryMessage.append("- Weekly Eco Task 2 Completed (+50 pts)\n");
        }
        if (chkWeekly3.isSelected()) { 
            accumulatedPoints += 50;
            summaryMessage.append("- Unplugged Idle Appliances Completed (+50 pts)\n");
        }

        // 📆 Monthly Tasks Section
        if (chkMonthly1.isSelected()) { 
            accumulatedPoints += 150;
            summaryMessage.append("- LED Bulbs Switch Completed (+150 pts)\n");
        }
        if (chkMonthly2.isSelected()) { 
            accumulatedPoints += 150;
            summaryMessage.append("- Continuous Tracking Streak Completed (+150 pts)\n");
        }
        if (chkMonthly3.isSelected()) { 
            accumulatedPoints += 150;
            summaryMessage.append("- E-Waste Recycling Completed (+150 pts)\n");
        }

        // Guard clause checking if nothing was checked
        if (accumulatedPoints == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Please check at least one completed challenge before submitting!", 
                "No Selection Found", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Save accumulated points directly to the real user account
        UserDAO dao = new UserDAO();
        boolean success = dao.addGreenPoints(currentUserId, accumulatedPoints);

        if (success) {
            summaryMessage.append("\nTotal Reward Balance: +").append(accumulatedPoints).append(" Green Points!");
            javax.swing.JOptionPane.showMessageDialog(this, 
                summaryMessage.toString(), 
                "Milestones Achieved 🎉", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // 🧼 Housekeeping reset: Cleanly uncheck rows after logging
            chkDaily1.setSelected(false);
            chkDaily2.setSelected(false);
            chkDaily3.setSelected(false);
            chkWeekly1.setSelected(false);
            chkWeekly2.setSelected(false);
            chkWeekly3.setSelected(false);
            chkMonthly1.setSelected(false);
            chkMonthly2.setSelected(false);
            chkMonthly3.setSelected(false);

            // 🔄 Automatically open an updated dashboard window to update counts and leaderboard placements in real-time
            new Dashboard(currentUserId).setVisible(true);
            this.dispose();

        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Database error tracking challenge submission results.", 
                "Database Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        Dashboard freshDashboardInstance = new Dashboard(this.userId); 
        freshDashboardInstance.setVisible(true);
        this.dispose(); // Close old checklist frame interface window resource context cleanly
    }//GEN-LAST:event_btnDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Challenges().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JCheckBox chkDaily1;
    private javax.swing.JCheckBox chkDaily2;
    private javax.swing.JCheckBox chkDaily3;
    private javax.swing.JCheckBox chkMonthly1;
    private javax.swing.JCheckBox chkMonthly2;
    private javax.swing.JCheckBox chkMonthly3;
    private javax.swing.JCheckBox chkWeekly1;
    private javax.swing.JCheckBox chkWeekly2;
    private javax.swing.JCheckBox chkWeekly3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
