/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sarit
 */
public class CreateAccount extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateAccount.class.getName());

    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createAccBtn1 = new javax.swing.JButton();
        fullname = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        confirmpassword = new javax.swing.JLabel();
        mobileno = new javax.swing.JLabel();
        mobileInput = new javax.swing.JTextField();
        nameInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        confirmPasswordInput = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Create Account");

        createAccBtn1.setBackground(new java.awt.Color(51, 102, 0));
        createAccBtn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        createAccBtn1.setForeground(new java.awt.Color(204, 255, 204));
        createAccBtn1.setText("Create Account");
        createAccBtn1.addActionListener(this::createAccBtn1ActionPerformed);

        fullname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        fullname.setText("Full Name");

        Email.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Email.setText("Email");

        password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password.setText("Password");

        confirmpassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        confirmpassword.setText("Confirm Password");

        mobileno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        mobileno.setText("Mobile No");

        mobileInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        nameInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        emailInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        passwordInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        confirmPasswordInput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createAccBtn1)
                .addGap(143, 143, 143))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobileno)
                            .addComponent(fullname, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(confirmpassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPasswordInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmPasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmpassword))
                .addGap(9, 9, 9)
                .addComponent(createAccBtn1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAccBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccBtn1ActionPerformed
        // TODO add your handling code here:
        String inputName = nameInput.getText().trim();
        String inputMobile = mobileInput.getText().trim();
        String inputEmail = emailInput.getText().trim();

        // Convert character arrays out of masked JPasswordFields
        String inputPass = new String(passwordInput.getPassword()).trim();
        String confirmPass = new String(confirmPasswordInput.getPassword()).trim();

        // 2. Perform vital local validation checks
        if (inputName.isEmpty() || inputMobile.isEmpty() || inputEmail.isEmpty() || inputPass.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "All fields are mandatory.", 
                    "Validation Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. Confirm Password Verification Check
        if (!inputPass.equals(confirmPass)) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Passwords do not match. Please re-enter.", 
                    "Validation Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. Send structured dataset to the DAO insertion block
        UserDAO userDAO = new UserDAO();
        boolean registrationSuccess = userDAO.registerUser(inputName, inputMobile, inputEmail, inputPass);

        // 5. Provide immediate interface feedback based on database operation result
        if (registrationSuccess) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Account registered successfully!", 
                    "Success", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            LoginModule lg = new LoginModule();
            lg.setVisible(true);
            this.dispose();
        }else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                    "Registration failed. That email address is already registered.", 
                    "Database Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_createAccBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreateAccount().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JPasswordField confirmPasswordInput;
    private javax.swing.JLabel confirmpassword;
    private javax.swing.JButton createAccBtn1;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel fullname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField mobileInput;
    private javax.swing.JLabel mobileno;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordInput;
    // End of variables declaration//GEN-END:variables
}
