/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Amgoth srinivas
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
public class Dashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());
    private int userId;
    /**
     * Creates new form Dashboard
     */
    public Dashboard(int sessionUserId) {
        initComponents();
        this.userId = sessionUserId;
        this.setLocationRelativeTo(null);
        
        new UserDAO().initializeDefaultChallenges(this.userId);
    
        // --- SYNCHRONIZE STRUTURE TITLES ---
        lblActiveChallanges.setText("Active Challenges"); 
        lblRank.setText("Your Rank"); // Instantly overrides the subtitle on screen load!
    
        loadDashboardStats(this.userId); 
    }
    
    // 2. Keep a fallback constructor so NetBeans GUI Builder preview doesn't break
    public Dashboard() {
        this(1); // Defaults to user_id = 1 for standalone layout preview testing
    }

   public void loadDashboardStats(int userId) {
        String queryTotal = "SELECT SUM(calculated_co2e) as total FROM emission_logs WHERE user_id = ?";

        // ✅ FIX: Checks both 'Active' and lowercase 'active' to prevent empty returns
        String queryChallenges = "SELECT COUNT(*) as active FROM user_challenges WHERE user_id = ? AND (status = 'Active' OR status = 'active')";

        String queryRank = "SELECT (SELECT COUNT(*) FROM users u2 WHERE u2.green_score > u1.green_score) + 1 AS ranking " +
                   "FROM users u1 WHERE u1.user_id = ?";

        try (Connection conn = DBConnection.getConnection()) {

            // 1. Total Footprint
            try (PreparedStatement pstmt = conn.prepareStatement(queryTotal)) {
                pstmt.setInt(1, userId);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        double total = rs.getDouble("total");
                        totalFootprintValue.setText(String.format("%.2f kg", total));
                    } else {
                        totalFootprintValue.setText("0.00 kg");
                    }
                }
            }

            // 2. Active Challenges (Fixed Component Target)
            try (PreparedStatement pstmt = conn.prepareStatement(queryChallenges)) {
                pstmt.setInt(1, userId);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        int activeCount = rs.getInt("active");
                        activeChallengesValue.setText(String.valueOf(activeCount)); 
                    } else {
                        activeChallengesValue.setText("0");
                    }
                }
            }

            // 3. Dynamic Rank Assignment
            try (PreparedStatement pstmt = conn.prepareStatement(queryRank)) {
                pstmt.setInt(1, userId);
                try (ResultSet rs = pstmt.executeQuery()) {
                    if (rs.next()) {
                        int dynamicRank = rs.getInt("ranking");
                        totaloffsetValue.setText("#" + dynamicRank);
                    } else {
                        totaloffsetValue.setText("N/A");
                    }
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    public void updateActiveChallengesCount(int userId) {
        String sql = "SELECT COUNT(*) AS total_active FROM user_challenges WHERE user_id = ? AND (status = 'Active' OR status = 'active')";

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement pstmt = conn.prepareStatement(sql)) {

            pstmt.setInt(1, userId);
            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    activeChallengesValue.setText(String.valueOf(rs.getInt("total_active")));
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
            activeChallengesValue.setText("0"); 
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logFootprintBtn = new javax.swing.JButton();
        leaderboardBtn = new javax.swing.JButton();
        challengesBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logOutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        card1 = new javax.swing.JPanel();
        totalFootprintValue = new javax.swing.JLabel();
        card2 = new javax.swing.JPanel();
        activeChallengesValue = new javax.swing.JLabel();
        card3 = new javax.swing.JPanel();
        totaloffsetValue = new javax.swing.JLabel();
        lblFootprint = new javax.swing.JLabel();
        lblActiveChallanges = new javax.swing.JLabel();
        lblRank = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        logFootprintBtn.setBackground(new java.awt.Color(51, 102, 0));
        logFootprintBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logFootprintBtn.setForeground(new java.awt.Color(204, 255, 204));
        logFootprintBtn.setText("Log Footprint");
        logFootprintBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logFootprintBtn.addActionListener(this::logFootprintBtnActionPerformed);

        leaderboardBtn.setBackground(new java.awt.Color(51, 102, 0));
        leaderboardBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        leaderboardBtn.setForeground(new java.awt.Color(204, 255, 204));
        leaderboardBtn.setText("Leaderboard");
        leaderboardBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leaderboardBtn.addActionListener(this::leaderboardBtnActionPerformed);

        challengesBtn.setBackground(new java.awt.Color(51, 102, 0));
        challengesBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        challengesBtn.setForeground(new java.awt.Color(204, 255, 204));
        challengesBtn.setText("Challenges");
        challengesBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        challengesBtn.addActionListener(this::challengesBtnActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("Dashboard");

        logOutBtn.setBackground(new java.awt.Color(51, 102, 0));
        logOutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logOutBtn.setForeground(new java.awt.Color(204, 255, 204));
        logOutBtn.setText("LogOut");
        logOutBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logOutBtn.addActionListener(this::logOutBtnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(logFootprintBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(leaderboardBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(challengesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(logOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(logFootprintBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(leaderboardBtn)
                .addGap(18, 18, 18)
                .addComponent(challengesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logOutBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setForeground(new java.awt.Color(0, 153, 51));

        logo.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        logo.setForeground(new java.awt.Color(51, 102, 0));
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setText("Your Carbon Impact");

        card1.setBackground(new java.awt.Color(255, 255, 255));
        card1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        totalFootprintValue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalFootprintValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalFootprintValue.setText("0.00 kg");

        javax.swing.GroupLayout card1Layout = new javax.swing.GroupLayout(card1);
        card1.setLayout(card1Layout);
        card1Layout.setHorizontalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalFootprintValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        card1Layout.setVerticalGroup(
            card1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalFootprintValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        card2.setBackground(new java.awt.Color(255, 255, 255));
        card2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        activeChallengesValue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        activeChallengesValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        activeChallengesValue.setText("0");

        javax.swing.GroupLayout card2Layout = new javax.swing.GroupLayout(card2);
        card2.setLayout(card2Layout);
        card2Layout.setHorizontalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activeChallengesValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        card2Layout.setVerticalGroup(
            card2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activeChallengesValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );

        card3.setBackground(new java.awt.Color(255, 255, 255));
        card3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        totaloffsetValue.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totaloffsetValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totaloffsetValue.setText("0");

        javax.swing.GroupLayout card3Layout = new javax.swing.GroupLayout(card3);
        card3.setLayout(card3Layout);
        card3Layout.setHorizontalGroup(
            card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totaloffsetValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
        );
        card3Layout.setVerticalGroup(
            card3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totaloffsetValue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
        );

        lblFootprint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFootprint.setForeground(new java.awt.Color(51, 102, 0));
        lblFootprint.setText("Total Footprint");

        lblActiveChallanges.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblActiveChallanges.setForeground(new java.awt.Color(51, 102, 0));
        lblActiveChallanges.setText("Active Challenges");

        lblRank.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblRank.setForeground(new java.awt.Color(51, 102, 0));
        lblRank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRank.setText("Rank");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(card1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblFootprint)))
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(card2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblActiveChallanges))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(card3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblRank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(logo)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logo)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(card1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(card2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(card3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFootprint)
                    .addComponent(lblActiveChallanges)
                    .addComponent(lblRank))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logFootprintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logFootprintBtnActionPerformed
        // TODO add your handling code here:
        new CarbonFootprint(this.userId).setVisible(true);
        this.dispose(); // Safely close your dashboard page window out of active system memory
    }//GEN-LAST:event_logFootprintBtnActionPerformed

    private void leaderboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderboardBtnActionPerformed
        // TODO add your handling code here:
        Leaderboard lb = new Leaderboard (this.userId);
        lb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_leaderboardBtnActionPerformed

    private void challengesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_challengesBtnActionPerformed
        // TODO add your handling code here:
        Challenges chh = new Challenges(this.userId);
        chh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_challengesBtnActionPerformed

    private void logOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutBtnActionPerformed
        // TODO add your handling code here:
        LoginModule lg = new LoginModule();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activeChallengesValue;
    private javax.swing.JPanel card1;
    private javax.swing.JPanel card2;
    private javax.swing.JPanel card3;
    private javax.swing.JButton challengesBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblActiveChallanges;
    private javax.swing.JLabel lblFootprint;
    private javax.swing.JLabel lblRank;
    private javax.swing.JButton leaderboardBtn;
    private javax.swing.JButton logFootprintBtn;
    private javax.swing.JButton logOutBtn;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel totalFootprintValue;
    private javax.swing.JLabel totaloffsetValue;
    // End of variables declaration//GEN-END:variables
}
